variables:
  QUICKLISP_ADD_TO_INIT_FILE: "true"

image: clfoundation/sbcl:latest

before_script:
  - install-quicklisp
  - git clone https://gitlab.com/dpflug/bemane ~/quicklisp/local-projects/

build:
  stage: build
  variables:
    LISP: sbcl
  script:
    - make build
  artifacts:
    paths:
      - bemane
