variables:
  QUICKLISP_ADD_TO_INIT_FILE: "true"

image: clfoundation/ccl:latest

before_script:
  - install-quicklisp
  - git clone https://gitlab.com/dpflug/bemane ~/quicklisp/local-projects/

.build:
  variables:
    LISP: ccl
  script:
    - make build
  after_script:
    - pwd
    - ls
    - ls src
  artifacts:
    paths:
      - src/bemane

test-build:
  extends: .build
  artifacts:
    name: "bemane-$CI_COMMIT_REF_SLUG"

linux-amd64-release:
  extends: .build
  artifacts:
    name: "bemane-linux-amd64-$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
